name: Try1

on:
  push:
    branches:
      - master


jobs:
  build:
    name: Build
    runs-on: self-hosted 
    permissions: read-all
    steps:
      - name: Build and analyze
        env:
         shell: powershell
        run: |
          C:\actions-runner\_work\eSHopOnWeb\eSHopOnWeb\.sonar\scanner\dotnet-sonarscanner begin /k:"vegasergio2851_eshop2_AYumRvsT_MDwPei2VGln" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"
          dotnet build
          C:\actions-runner\_work\eSHopOnWeb\eSHopOnWeb\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
